name: Tests
on:
  push:
    branches-ignore:
      - 'tmp-*'
  pull_request:
    branches-ignore:
      - 'tmp-*'

jobs:
  tests:
    name: CI
    runs-on: ubuntu-latest
    services:
      redis:
        image: 'redis'
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
        ports:
          - 6379:6379
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.10'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go mod download

      - name: Run CI lint
        run: sh helper/golint.sh

      - name: Run test cover
        run: sh helper/test-cover.sh
